### ISSUE TITLE
Crashing on 1.19.2

### ISSUE THREAD

**Issue by XepherTim** [Andrew6rant/MC-237017-Fix#1]
Mod seems to crash on 1.19.2. 

Here's the log for Fabric Loader 14.14 and Fabric API 0.75.1

https://gist.github.com/XepherTim/cc8dad3d173117acfc7ff24da5db5279

I also tried with a few other loader versions, but it didn't change anything (don't know if it would, but worth a shot).

**Comment by LKD-PIX** [comment]
can confirm this

**Comment by Andrew6rant** [comment]
Whoops! I didn't have notifications enabled for this repository. Can you check if the latest Actions jar (tagged with 1.19.2-and-older) work? https://github.com/Andrew6rant/MC-237017-Fix/actions?query=branch%3A1.19.2-and-older

**Comment by LKD-PIX** [comment]
seems to work

**Comment by XepherTim** [comment]
Same here, thanks!
